[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diffpfa"
version = "0.1.0"
description = "PyTorch Polar Format Algorithm (PFA) CPHD Image Processor"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "numpy",
    "scipy",
    "lxml",
    "matplotlib"
]

[project.optional-dependencies]
sarkit = ["sarkit"]
sarpy = ["sarpy"]
all = ["sarkit", "sarpy"]
dev = ["pytest"]

[project.scripts]
diffpfa = "diffpfa.cli:main"
